data-y+=htdocs/apps/signin.html
data-y+=htdocs/apps/ouiweb.html
htdocs/apps/ouiweb.html_ALIAS+=index.html
data-y+=htdocs/apps/ouiweb.json
data-y+=htdocs/apps/ouifile.html
data-y+=htdocs/apps/js/ouishell.js
data-y+=htdocs/apps/images/ouifile.png
data-$(ALBUM)+=htdocs/apps/ouialbum.html
data-$(ALBUM)+=htdocs/apps/images/ouialbum.png
data-$(CHAT)+=htdocs/apps/ouichat.html
data-$(CHAT)+=htdocs/apps/js/ouichat.js
data-$(CHAT)+=htdocs/apps/images/ouichat.png
data-$(PLAYMUSIC)+=htdocs/apps/ouiplaymusic.html
data-$(PLAYMUSIC)+=htdocs/apps/images/ouiplaymusic.png
data-$(EDIT)+=htdocs/apps/ouiedit.html

subdir-y+=bootstrap.mk
subdir-y+=jquery.mk
